#Created by Junier Amorim
#Process data generated by RePast
#After the first analysis, A2 was removed. A3 was renamed to A2
#

dataset <- data.frame(matrix(ncol = 20, nrow = 500))
OUTLIERS <- FALSE
names(dataset) <- c("A1","A2","A1","A2","A1","A2","A1","A2","A1","A2","A1","A2","A1","A2","A1","A2","A1","A2","A1","A2")
metricsName <- c("Reconfigurations","Maneuvers","Timeliness","Resilience","Effectiveness","Reward")
scenarios <- c(1,2,3,4,5,6,7,8,9,10)  
NoS <- length(scenarios)
path <- '/Users/junier/git/PIBIC-C2/Results/'
process <- TRUE # Remove outliers (greater than 2*standard deviation)
metrics <- c(1,2,3,5,6) #It was added metric 6 - REWARD
for(j in metrics){
  for(i in scenarios){
    file <- paste0(path,i,'/','M',j)
    data <- read.csv(file = file, sep=';', header = FALSE)
    for(A in c(1,2)){ #get each treatment for Agility Method
      #d = ncol(data[A,]) - 1 #to remove the last semicolon
      d = ncol(data[A,]) 
      #mat <- as.matrix(data[j,1:d])
      mean <- round(rowMeans(data[A,], na.rm = TRUE), 1)
      sd <- round(sd(data[A,], na.rm = TRUE), 2)
      #print(specify_decimal(rowMeans(data[2,], na.rm = TRUE), 1))
      #print(specify_decimal(sd(mat),2))
      if(process){
        threshold_min <- mean - sd
        threshold_max <- mean + sd
        for(pos in seq(d)){
          if((data[A,pos] <= threshold_min)||(data[A,pos] >= threshold_max)){
            data[A,pos] <- mean;
          }
        }
      }
      
      for(pos in seq(d)){
        dataset[pos,2*(i-1)+A] <- data[A,pos]
      }
    }
  }
  
  name<- paste0("Boxplot_M",j,".png")
  png(name)
  par(cex.lab=1.3) # is for y-axis
  par(cex.axis=1.3) # is for x-axis
  par(cex.main=1.5)
  g <- boxplot(dataset, xaxt="n", ylim = c(min(dataset[]), max(dataset[])), col = c("white","darkgrey"), outline=OUTLIERS, ylab =metricsName[j], xlab ="Scenarios",main=paste0(metricsName[j],"(M",j,")"))
  axis(1,at=seq(1.5,20,2), labels=c(1,2,3,4,5,6,7,8,9,10))+abline(v=seq(0.5,21,2),lty=3,col="blue")
  legend("bottomleft",legend=c("A1", "A2"),
         col=c("A1", "A2"),fill=c("white","darkgrey"),
         title="Action Methods", text.font=4, inset = .15,horiz=TRUE, cex=1)

  #show(g)
  dev.off()
 
}
#g <- boxplot(dataset, las = 1, ylim = c(0, 30), col = c("white","darkgrey"), par(mar = c(6, 5, 2, 0)+ 0.1), ylab ="REWARD", main="Reward(M6)", xlim=c(1,20))+abline(v=seq(1,20,2),lty=2,col="blue")+axis(1,at=c(1,3,5,7,9,11,13,15,17,19), labels=c("1","1","1","1","1","1","1","1","1","1"))





