#Created by Junier Amorim
#Process data generated by RePast
#Each line in file Mx is a treatment of Agility Method (A1, A2 and A3) applied to a scenario
#After the first analysis, A2 was removed. A3 was renamed to A2
#
scenarios <- c(1,2,3,4,5,6,7,8,9,10)
#scenarios <- c(1) #Number of Scenarios to be interact. It is the same number of folders in Eclipse Workspace
NoS <- length(scenarios)
path <- '/Users/junier/git/PIBIC-C2/Results/'
metrics <- c(1,2,3,5,6) #It was added metric 6 - REWARD
#specify_decimal <- function(x, k) trimws(format(round(x, k), nsmall=k)) #function used to format the numbers in results
for(j in metrics){
  for(i in scenarios){
    file <- paste0(path,i,'/','M',j)
    data <- read.csv(file = file, sep=';', header = FALSE)
    file2 <- paste0(path,'mean_M',j)
    data2 <- read.csv(file = file2, sep=' ', header = TRUE)
    
    #result <- wilcox.test(as.numeric(data[1,]), mu=data2[i,2], alternative = "less")
    result <- wilcox.test(as.numeric(data[1,]), mu = median(as.numeric(data[2,])), alternative = "two.sided")
    
    cat(paste0("==> Scenario ",i," (M",j,"):"))
    cat("\n")
    if(result$p.value >= 0.05){
      print(result)
    }
  }
}

