#Created by Junier Amorim
#Process data generated by RePast
#Each line in file Mx is a treatment of Agility Method (A1, A2 and A3) applied to a scenario
#After the first analysis, A2 was removed. A3 was renamed to A2
#
scenarios <- c(1,2,3,4,5,6,7,8,9,10)
#scenarios <- c(1) #Number of Scenarios to be interact. It is the same number of folders in Eclipse Workspace
NoS <- length(scenarios)
path <- '/Users/junier/git/PIBIC-C2/Results/'
metrics <- c(1,2,3,4,5,6) #It was added metric 6 - REWARD
line1 <- "\\bf{A1} ";
line2 <- "\\bf{A2} ";
for(i in scenarios){
  for(j in metrics){
    file1 <- paste0(path,'mean_M',j)
    file2 <- paste0(path,'sd_M',j)
    mean <- read.csv(file = file1, sep=' ', header = TRUE)
    sd <- read.csv(file = file2, sep=' ', header = TRUE)
     line1 <- paste0(line1," & ", sprintf("%.1f",mean[i,1])," ($","\\","pm$",sprintf("%.1f",sd[i,1]),") ")
    line2 <- paste0(line2," & ", sprintf("%.1f",mean[i,2])," ($","\\","pm$",sprintf("%.1f",sd[i,2]),") ")
  }
  cat(paste("% Scenario ",i,"\n"))
  cat(paste0(line1, " \\","\\"))
  cat("\n")
  cat(paste0(line2, " \\","\\ [1ex]"))
  cat("\n")
  line1 <- "\\bf{A1} ";
  line2 <- "\\bf{A2} ";
  
  #output <- paste0(path,'mean_M',j)
  #write.table(means,file=output)
}