#Created by Junier Amorim
#Process data generated by RePast
#After the first analysis, A2 was removed. A3 was renamed to A2
#
library(ggplot2)
library(ggpubr)
scenarios <- c(1,2,3,4,5,6,7,8,9,10)
#scenarios <- c(1) #Number of Scenarios to be interact. It is the same number of folders in Eclipse Workspace
NoS <- length(scenarios)
path <- '/Users/junier/git/PIBIC-C2/Results/'
metrics <- c(1,2,3,4,6) #It was added metric 6 - REWARD; metric 5 is RESILIENCE
metricsName <- c("Reconfigurations","Maneuvers","Engagement Time","Effectiveness","Resilience","Reward")
#agility_method <- rep(c("A1","A2","A3"),length(scenarios))
agility_method <- rep(c("A1","A2"),length(scenarios))

for(i in metrics){
  file1 <- paste0(path,'mean_M',i)
  file2 <- paste0(path,'sd_M',i)
  mean_data <- read.table(file = file1, header = TRUE)
  sd_data <- read.table(file = file2, header = TRUE)
  
  scenario <- c()
  value_mean <- c()
  value_sd <- c()
  
  #creating scenarios and reading mean values
  for(j in scenarios){
    #scenario <- c(scenario,rep(j,3)) #3 represents the treatments quantity (A1, A2, A3)
    scenario <- c(scenario,rep(j,2)) #2 represents the treatments quantity (A1, A3)
    
    value_mean <- c(value_mean, as.numeric(mean_data[j,]))
    value_sd <- c(value_sd, as.numeric(sd_data[j,]))
  }
  
  data <- data.frame(scenario, agility_method, value_mean)
  
  name<- paste0("Result_M",i,".png")
  #name<- paste0("Result_M",i,".pdf")
  
  print(data)
  
  #graph <- ggplot(data, aes(fill=agility_method, y=value_mean, x=scenario))+geom_bar(position="dodge", stat="identity")+labs(title=paste0("Metric M",i," - ",metricsName[i]), x="Scenarios", y="Metric")+xlim(0,length(scenarios)+1)+geom_errorbar(aes(ymin=value_mean-value_sd, ymax=value_mean+value_sd), width=.2,position=position_dodge(.9)) + scale_x_discrete(name ="Scenarios", limits=scenarios)
  graph <- ggplot(data, aes(fill=agility_method, y=value_mean, x=scenario))+geom_bar(position="dodge", stat="identity", color="black")+labs(fill="Action \n Method", x="Scenario", y=paste0(metricsName[i]," (M",i,")"))+geom_errorbar(aes(ymin=value_mean-value_sd, ymax=value_mean+value_sd), width=.2,position=position_dodge(.9)) + scale_x_discrete(limits=as.factor(scenarios)) + 
    #+scale_fill_brewer(palette="Dark2")
    theme(axis.text.x = element_text(color = "grey20", size = 13, angle = 0, hjust = .5, vjust = .5, face = "plain"),
          axis.text.y = element_text(color = "grey20", size = 13, angle = 0, hjust = 1, vjust = 0, face = "plain"),  
          axis.title.x = element_text(color = "grey20", size = 16, angle = 0, hjust = .5, vjust = 0, face = "plain"),
          axis.title.y = element_text(color = "grey20", size = 16, angle = 90, hjust = .5, vjust = .5, face = "plain"),
          legend.text=element_text(size=14),legend.title=element_text(size=14))
  
  multi.page <- ggarrange(graph, nrow=1, ncol =1)
  ggexport(multi.page, filename = name)
}
