#Created by Junier Amorim
#Process data generated by RePast
#Each line in file Mx is a treatment of Agility Method (A1, A2 and A3) applied to a scenario
#After the first analysis, A2 was removed. A3 was renamed to A2
#
scenarios <- c(1,2,3,4,5,6,7,8,9,10)
#scenarios <- c(1) #Number of Scenarios to be interact. It is the same number of folders in Eclipse Workspace
NoS <- length(scenarios)
path <- '/Users/junier/git/PIBIC-C2/Results/'
process <- TRUE # Remove outliers (greater than 2*standard deviation)
metrics <- c(1,2,3,4,6) #It was added metric 6 - REWARD; metric 5 is RESILIENCE
#specify_decimal <- function(x, k) trimws(format(round(x, k), nsmall=k)) #function used to format the numbers in results
for(j in metrics){
  #means <- matrix(nrow=NoS, ncol=3, dimnames = list(c(seq(NoS)), c("A1","A2","A3")))
  #sd <- matrix(nrow=NoS, ncol=3, dimnames = list(c(seq(NoS)), c("A1","A2","A3")))
  means <- matrix(nrow=NoS, ncol=2, dimnames = list(c(seq(NoS)), c("A1","A2")))
  sd <- matrix(nrow=NoS, ncol=2, dimnames = list(c(seq(NoS)), c("A1","A2")))
  for(i in scenarios){
    file <- paste0(path,i,'/','M',j)
    data <- read.csv(file = file, sep=';', header = FALSE)
    #for(A in c(1,2,3)){ #get each treatment for Agility Method
    for(A in c(1,2)){ #get each treatment for Agility Method
      d = ncol(data[A,]) - 1 #to remove the last semicolon
      #mat <- as.matrix(data[j,1:d])
      means[i,A] <- round(rowMeans(data[A,], na.rm = TRUE), 1)
      sd[i,A] <- round(sd(data[A,], na.rm = TRUE), 2)
      #print(specify_decimal(rowMeans(data[2,], na.rm = TRUE), 1))
      #print(specify_decimal(sd(mat),2))
      if(process){
        sd2 <- sd[i,A]
        med <- means[i,A]
        threshold_min <- med - sd2
        threshold_max <- med + sd2
        for(pos in seq(d)){
          if((data[A,pos] <= threshold_min)||(data[A,pos] >= threshold_max)){
            data[A,pos] <- med;
          }
        }
        means[i,A] <- round(rowMeans(data[A,], na.rm = TRUE), 1)
        sd[i,A] <- round(sd(data[A,], na.rm = TRUE), 2)
      }
      
    }
    #means <- as.numeric(means)
    #sd <- as.numeric(sd)
  }
  print(paste0("METRIC => ",j))
  output <- paste0(path,'mean_M',j)
  write.table(means,file=output)
  output <- paste0(path,'sd_M',j)
  write.table(sd,file=output)
  print(means)
  print(sd)
}

